# Handle git submodules yourself
git:
  submodules: false

language: android

jdk:
  - oraclejdk8

android:
  components:
    - tools
    - build-tools-23.0.1
    - android-23
    - extra-android-m2repository

before_install:
  # Android SDK configuration
  - printenv
  - export ANDROID_SDK_ROOT=/usr/local/android-sdk
  - export PATH=$PATH:$ANDROID_SDK_ROOT/tools:$ANDROID_SDK_ROOT/platform-tools

  # Android NDK configuration for Box2D
  - printenv
  - echo `pwd`
  - wget http://dl.google.com/android/ndk/android-ndk-r9-linux-x86.tar.bz2
  - chmod a+x android-ndk-r9-linux-x86.tar.bz2
  - tar -xf android-ndk-r9-linux-x86.tar.bz2 -C $ANDROID_SDK_ROOT/ndk-bundle_r9
  - ls -al $ANDROID_SDK_ROOT/ndk-bundle/android-ndk-r14b
  - export NDK_ROOT_R9=$ANDROID_SDK_ROOT/ndk-bundle/android-ndk-r14b
  - echo $NDK_ROOT_R9
  - export PATH=$PATH:$NDK_ROOT_R9
  - echo $PATH

  # Android NDK configuration 
  - printenv
  - echo `pwd`
  - wget https://dl.google.com/android/repository/android-ndk-r14b-linux-x86_64.zip
  - chmod a+x android-ndk-r14b-linux-x86_64.zip
  - unzip -qq android-ndk-r14b-linux-x86_64.zip -d $ANDROID_SDK_ROOT/ndk-bundle
  - ls -al $ANDROID_SDK_ROOT/ndk-bundle/android-ndk-r14b
  - export NDK_ROOT=$ANDROID_SDK_ROOT/ndk-bundle/android-ndk-r14b
  - echo $NDK_ROOT
  - export PATH=$PATH:$NDK_ROOT
  - echo $PATH

  - export ANT_ROOT=/usr/share/ant/bin
  - export PATH=$PATH:$ANT_ROOT
  - cd ..
  - echo `pwd`
  - printenv

script:
  - cocos compile -p android

notifications:
  email: false